name: Pull Request Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Verify Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Test Windows build
        run: GOOS=windows GOARCH=amd64 go build -o test.exe
      
      - name: Test Linux build
        run: GOOS=linux GOARCH=amd64 go build -o test
      
      - name: Clean up test files
        run: rm -f test.exe test 