name: Build and Push Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o cs2-translate_${{ steps.get_version.outputs.VERSION }}_windows_x64.exe
      
      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o cs2-translate_${{ steps.get_version.outputs.VERSION }}_linux_x64
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          files: |
            cs2-translate_${{ steps.get_version.outputs.VERSION }}_windows_x64.exe
            cs2-translate_${{ steps.get_version.outputs.VERSION }}_linux_x64
          draft: true
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 